### ISSUE TITLE
Questions about occupied BEV proportion

### ISSUE THREAD

**Issue by woxihuanjiangguo** [mengtan00/SA-BEV#2]
Hello author, thanks for your great work. In the paper, it is mentioned that with two thresholds, the valid virtual points are reduced to 1.8% compared with the original version. I wonder what is the proportion of valid BEV grids compared with the baseline.

**Comment by mengtan00** [comment]
It should be larger than 1.8%, since the pseudo point per grid is reduced in SA-BEV, but still a very small proportion. You can save the BEV features and compare the sum of the valid BEV grids.
