### ISSUE TITLE
How can I get "gt_semantic"

### ISSUE THREAD

**Issue by Da1symeeting1** [mengtan00/SA-BEV#4]
@mengtan00 In the train pipeline there is a key "gt_semantic", how can i get it , could you please link the code ? thanks .

**Comment by mengtan00** [comment]
Please follow the step 3 in the get started.

**Comment by mengtan00** [comment]
line 1044-1053 in mmdet/datasets/pipelines/loading.py transforms point label into gt_semantic

**Comment by Da1symeeting1** [comment]
thx for the reply! so kind
