### ISSUE TITLE
Questions about the ablation study in SA-BEV

### ISSUE THREAD

**Issue by kingofstu** [mengtan00/SA-BEV#6]
Hi,
I apologize for bothering you again. I noticed that your code 'SABEV' in 'sabev-r50.py' inherits from 'BEVDepth4D'. Then I wonder if the results of 'BEVDepth' in 'Table 3: Ablation Study of Component in SA-BEV on the nuScenes Validation Set' are reproduced from 'BEVDepth4D' without the CBGS strategy.

Looking forward to your reply. Best wishes!

**Comment by mengtan00** [comment]
Yes, as mentioned in Implementation Detail.

**Comment by kingofstu** [comment]
> Yes, as mentioned in Implementation Detail.

I also noticed that the results of BEVDepth in 'SA-BEV, Table 3' and in 'Geo-BEV, Table 3' are different, which are '0.330mAP, 0.436NDS';  '0.337mAP, 0.456NDS' respectively, what caused this phenomenon?

**Comment by mengtan00** [comment]
0.33 is official, 0.337 is reproduced.

**Comment by kingofstu** [comment]
Thanks!
